// Data: cycle phases, recipes, brand mapping, stores, diets, cuisines, allergens

const PHASES = [
  {
    id: 'menstrual',
    name: 'Menstrual',
    range: [1, 5],
    dosha: 'Vata',
    color: 'oklch(0.62 0.11 35)',
    soft: 'oklch(0.93 0.035 40)',
    headline: 'Warm, ground, replenish.',
    body: 'Estrogen and progesterone are at baseline. The body is shedding tissue and losing iron. Digestion (Agni) runs low — favor warm, cooked, deeply nourishing meals over raw or cold.',
    gutFocus: 'Gut lining is most vulnerable. Prioritise bone broths, long-simmered legumes, and collagen-rich foods rich in L-glutamine to repair the intestinal mucosa. Avoid raw salads and cold drinks — they suppress Agni and worsen cramping. Slow gut motility can alternate with urgency; warm, easy-to-digest meals reduce this variability.',
    ayurvedicFocus: 'Vata dominates — the wind/space element governs movement and the nervous system. Ground it with heavy, unctuous, warm foods. Ghee is medicine. Mung dal is the ideal reset meal. Avoid all dry, rough, cold, or raw textures. Spice gently with cumin, ginger, and black pepper to rekindle digestive fire.',
    needs: ['Iron', 'Zinc', 'L-Glutamine', 'Warming spices', 'Bone broth'],
    avoid: ['Raw salads', 'Cold drinks', 'Dry crackers', 'Cruciferous raw veg'],
    carbState: 'Moderate, clean, comforting carbs allowed at breakfast & lunch.',
    seed: '1 tbsp ground flax + 1 tbsp pumpkin',
  },
  {
    id: 'follicular',
    name: 'Follicular',
    range: [6, 13],
    dosha: 'Kapha',
    color: 'oklch(0.58 0.09 140)',
    soft: 'oklch(0.93 0.030 140)',
    headline: 'Light, vibrant, fermented.',
    body: 'Estrogen rises to build the uterine lining. Insulin sensitivity is at its monthly peak — the body handles clean complex carbs exceptionally well. Feed the estrobolome.',
    gutFocus: 'The Estrobolome — the subset of gut bacteria that metabolise and eliminate used estrogen — is the focus. Feed it with diverse plant fibers and fermented foods (sauerkraut, kefir, kimchi). Cruciferous vegetables (broccoli, sprouts, rocket) support liver Phase II detoxification of estrogen. Target 30+ distinct plant foods this week to maximise microbiome diversity.',
    ayurvedicFocus: 'Kapha dominates — heavy, stable, moist earth energy. Counter it with light, vibrant, slightly bitter, and lightly spiced foods. Use warming ginger and cinnamon to keep digestion crisp without overheating. Spring-like foods mirror this phase: sprouts, micro-greens, light grains.',
    needs: ['Fermented foods', 'Cruciferous veg', 'Sprouts', 'Vibrant plant diversity'],
    avoid: ['Heavy, oily foods', 'Excess dairy', 'Refined grains'],
    carbState: 'Highest tolerance for vibrant, clean complex carbs.',
    seed: '1 tbsp ground flax + 1 tbsp pumpkin',
  },
  {
    id: 'ovulatory',
    name: 'Ovulatory',
    range: [14, 17],
    dosha: 'Pitta (entry)',
    color: 'oklch(0.76 0.10 88)',
    soft: 'oklch(0.94 0.040 88)',
    headline: 'Cool, antioxidant, bright.',
    body: 'Estrogen peaks and drops; LH triggers ovulation. Heat can accumulate — balance with cooling herbs (cilantro, mint, fennel) and high-antioxidant produce.',
    gutFocus: 'High antioxidant density clears systemic inflammation that peaks at ovulation. Prioritise soluble and insoluble fibers to bind to deactivated hormones in the bowel and prevent them from being reabsorbed (enterohepatic recirculation). Flaxseed, psyllium, and resistant starches are excellent here.',
    ayurvedicFocus: 'Pitta begins to rise — the fire element governs transformation. Excess heat can manifest as inflammation, skin breakouts, or irritability. Cool the system with cilantro, mint, fennel, cucumber, and lime. Avoid excessively spicy, sour, or pungent foods. Bitter greens (rocket, dandelion) support liver bile flow.',
    needs: ['Vitamin E', 'Antioxidants', 'Cooling herbs', 'Bitter greens', 'Soluble fiber'],
    avoid: ['Overly spicy foods', 'Excess heat', 'Alcohol'],
    carbState: 'Moderate carbs at breakfast & lunch.',
    seed: '1 tbsp sesame + 1 tbsp sunflower',
  },
  {
    id: 'luteal',
    name: 'Luteal',
    range: [18, 28],
    dosha: 'Pitta + Vata',
    color: 'oklch(0.62 0.08 230)',
    soft: 'oklch(0.93 0.025 230)',
    headline: 'Slow, magnesium, steady.',
    body: 'Progesterone peaks. Critical IR factor: progesterone increases insulin resistance and provokes carb cravings. Do not aggressively restrict — provide slow-burning, high-fiber, low-glycemic carbs to steady serotonin without spiking insulin.',
    gutFocus: 'Progesterone slows smooth muscle contraction, directly slowing intestinal motility — bloating and constipation are common. Counter this with high-magnesium foods (spinach, pumpkin seeds, raw cacao), soluble fiber (chia, flax, psyllium), and Vitamin B6-rich foods. Carminative spices (fennel, cardamom, ginger) relieve gas and bloating mechanically.',
    ayurvedicFocus: 'Pitta and Vata both rise — fire creates inflammation and wind creates anxiety and bloating. Warm, grounding, gently spiced foods are medicine: cinnamon for blood sugar, turmeric for inflammation, fenugreek for insulin sensitivity, cardamom and ginger for bloating. Slow-cooked squash, legumes, and warm grain dishes anchor both doshas.',
    needs: ['Magnesium', 'Vitamin B6', 'Cinnamon', 'Turmeric', 'Soluble fiber', 'Slow carbs'],
    avoid: ['Refined sugar', 'Late-night carbs', 'Aggressive restriction', 'Raw cold foods'],
    carbState: 'Complex, high-fiber, slow-burning carbs at breakfast & lunch (squash, quinoa, legumes).',
    seed: '1 tbsp sesame + 1 tbsp sunflower',
  },
];

function phaseForDay(day, length = 28) {
  const d = ((day - 1) % length) + 1;
  const pct = d / length;
  if (pct <= 5 / 28) return PHASES[0];
  if (pct <= 13 / 28) return PHASES[1];
  if (pct <= 17 / 28) return PHASES[2];
  return PHASES[3];
}

// Plant food count = distinct whole plant ingredients per recipe (for 30-plant/week goal)
const RECIPES = [
  {
    id: 'r-warming-mung-dal',
    title: 'Golden Mung Dal with Charred Greens',
    source: 'Sallys Welt',
    author: 'Sally Özcan',
    sourceUrl: 'https://sallys-blog.de/rezepte/indisches-linsen-curry-mit-warmem-tomaten-salat',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-7cac56f4bfd5?fit=crop&w=800&h=600&q=80',
    cuisine: 'south-asian',
    minutes: 35,
    servings: 2,
    protein: 32,
    carbs: 38,
    fat: 18,
    meal: 'lunch',
    phases: ['menstrual', 'luteal'],
    plantCount: 6,
    tags: ['Ayurvedic-spiced', 'Gut-healing', 'Warming', 'Gluten-free'],
    ingredients: [
      { item: 'Split yellow mung dal', amount: '150 g', brand: { REWE: 'REWE Bio Mung Dal', Edeka: 'Edeka Bio Hülsenfrüchte', Alnatura: 'Alnatura Mungbohnen' } },
      { item: 'Ghee', amount: '2 tbsp', brand: { REWE: 'REWE Bio Ghee', Edeka: 'GUT&GÜNSTIG Butterschmalz', Alnatura: 'Alnatura Ghee' } },
      { item: 'Fresh ginger', amount: '15 g', brand: { REWE: 'REWE Bio Ingwer', Edeka: 'Edeka Bio Ingwer', Alnatura: 'Alnatura Ingwer' } },
      { item: 'Turmeric', amount: '1 tsp', brand: { REWE: 'REWE Bio Kurkuma', Edeka: 'Edeka Kurkuma', Alnatura: 'Alnatura Bio Kurkuma' } },
      { item: 'Cumin seeds', amount: '1 tsp', brand: { REWE: 'REWE Bio Kreuzkümmel', Edeka: 'Edeka Kreuzkümmel', Alnatura: 'Alnatura Kreuzkümmel' } },
      { item: 'Lacinato kale', amount: '1 bunch', brand: { REWE: 'REWE Bio Schwarzkohl', Edeka: 'Edeka Bio Grünkohl', Alnatura: 'Alnatura Grünkohl' } },
      { item: 'Cilantro', amount: '½ bunch', brand: { REWE: 'REWE Bio Koriander', Edeka: 'Edeka Bio Koriander', Alnatura: 'Alnatura Koriander' } },
    ],
    steps: [
      'Rinse the mung dal until the water runs clear. Soak 15 minutes while you prep.',
      'Melt ghee in a heavy pot over medium heat. Add cumin seeds; let them sputter 30 seconds.',
      'Grate in the ginger, add turmeric, and stir 20 seconds — until the kitchen smells like a temple.',
      'Drain the dal and add it with 600 ml of just-boiled water. Simmer covered, 25 minutes, until soft.',
      'Strip the kale, tear into large pieces, and char in a dry cast-iron pan until edges blister.',
      'Spoon dal into warm bowls. Top with kale, cilantro, a final drizzle of ghee, and a crack of black pepper.',
    ],
    notes: 'Stir 1 tbsp ground flax + 1 tbsp pumpkin seeds in at the end during Menstrual or Follicular phase. Mung dal is the single most Ayurvedic gut-reset food — deeply nourishing, easy to digest, and anti-inflammatory.',
  },
  {
    id: 'r-roasted-squash',
    title: 'Roasted Kabocha, Tahini, Sumac',
    source: 'Kitchen Stories',
    author: 'Hanna Reder',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/mashed-kabocha-squash-a046',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?fit=crop&w=800&h=600&q=80',
    cuisine: 'middle-east',
    minutes: 45,
    servings: 2,
    protein: 28,
    carbs: 42,
    fat: 22,
    meal: 'lunch',
    phases: ['luteal'],
    plantCount: 5,
    tags: ['Seasonal', 'Magnesium-rich', 'Gut-healing', 'Vegan', 'Gluten-free'],
    ingredients: [
      { item: 'Kabocha squash', amount: '½', brand: { REWE: 'REWE Bio Hokkaido', Edeka: 'Edeka Bio Kürbis', Alnatura: 'Alnatura Hokkaido-Kürbis' } },
      { item: 'Extra virgin olive oil', amount: '3 tbsp', brand: { REWE: 'REWE Bio Olivenöl Nativ Extra', Edeka: 'BIO WERTKOST Olivenöl', Alnatura: 'Alnatura Olivenöl Nativ Extra' } },
      { item: 'Tahini', amount: '3 tbsp', brand: { REWE: 'REWE Bio Tahini', Edeka: 'Bio Sesammus', Alnatura: 'Alnatura Sesammus' } },
      { item: 'Cooked chickpeas', amount: '250 g', brand: { REWE: 'REWE Bio Kichererbsen', Edeka: 'Edeka Bio Kichererbsen', Alnatura: 'Alnatura Kichererbsen' } },
      { item: 'Sumac', amount: '1 tsp', brand: { REWE: 'Just Spices Sumach', Edeka: 'Ankerkraut Sumach', Alnatura: 'Alnatura Sumach' } },
      { item: 'Lacto-fermented red cabbage', amount: '4 tbsp', brand: { REWE: 'Schwarzwaldhof Sauerkraut', Edeka: 'Mildessa Rotkohl', Alnatura: 'Alnatura Rotkrautsalat' } },
    ],
    steps: [
      'Heat the oven to 220°C. Slice the kabocha into half-moons; toss with olive oil and salt.',
      'Roast 25 minutes, flipping once, until the skin blisters and the flesh collapses to a fork.',
      'Whisk tahini with lemon, a pinch of salt, and warm water until it falls in ribbons.',
      'Warm chickpeas in a dry skillet with sumac and a little olive oil, 3 minutes.',
      'Plate the squash, spoon tahini, scatter chickpeas, finish with fermented cabbage.',
    ],
    notes: 'The lacto-fermented cabbage adds a live probiotic hit that directly feeds the Estrobolome. Tahini is sesame in whole form — your luteal seed cycling built into the recipe.',
  },
  {
    id: 'r-folli-bowl',
    title: 'Sprouted Lentil & Beet Probiotic Bowl',
    source: 'REWE Rezepte',
    author: 'REWE Küche',
    sourceUrl: 'https://www.rewe.de/rezepte/rote-linsen-salat-mit-roter-beete/',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?fit=crop&w=800&h=600&q=80',
    cuisine: 'german',
    minutes: 25,
    servings: 2,
    protein: 30,
    carbs: 40,
    fat: 14,
    meal: 'lunch',
    phases: ['follicular'],
    plantCount: 7,
    tags: ['Estrobolome', 'Probiotic', 'Gut-healing', 'Fermented', 'Gluten-free', 'Vegetarian'],
    ingredients: [
      { item: 'Sprouted green lentils', amount: '200 g', brand: { REWE: 'REWE Bio Linsen', Edeka: 'Edeka Bio Berglinsen', Alnatura: 'Alnatura Berglinsen' } },
      { item: 'Roasted beets', amount: '2 medium', brand: { REWE: 'REWE Bio Rote Bete', Edeka: 'Edeka Bio Rote Bete', Alnatura: 'Alnatura Rote Bete' } },
      { item: 'Kefir dressing', amount: '4 tbsp', brand: { REWE: 'Andechser Bio Kefir', Edeka: 'Söbbeke Kefir', Alnatura: 'Andechser Natur Kefir' } },
      { item: 'Dill', amount: '½ bunch', brand: { REWE: 'REWE Bio Dill', Edeka: 'Edeka Bio Dill', Alnatura: 'Alnatura Dill' } },
      { item: 'Pumpkin seeds', amount: '2 tbsp', brand: { REWE: 'REWE Bio Kürbiskerne', Edeka: 'Seeberger Kürbiskerne', Alnatura: 'Alnatura Kürbiskerne' } },
    ],
    steps: [
      'Cook lentils in salted water 18 minutes until tender but holding shape. Drain and cool slightly.',
      'Roast or use jarred beets; cut into chunky wedges.',
      'Whisk kefir with lemon, mustard, dill, salt, pepper.',
      'Toss lentils with half the dressing; plate with beets, more dressing, toasted pumpkin seeds.',
    ],
    notes: 'Kefir introduces live Lactobacillus directly to the gut. Beets contain betaine, which supports liver methylation and estrogen detox. The pumpkin seeds deliver your follicular-phase flax/pumpkin seed cycling dose.',
  },
  {
    id: 'r-dinner-cod',
    title: 'Pan-Seared Cod, Brown Butter Greens',
    source: 'Kitchen Stories',
    author: 'Ruby Goss',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/5-ingredient-one-pan-tomato-braised-cod',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?fit=crop&w=800&h=600&q=80',
    cuisine: 'german',
    minutes: 20,
    servings: 2,
    protein: 36,
    carbs: 8,
    fat: 26,
    meal: 'dinner',
    phases: ['menstrual', 'follicular', 'ovulatory', 'luteal'],
    plantCount: 4,
    tags: ['Dinner-safe', 'Zero starch', 'Low-FODMAP', 'Gluten-free', 'Dairy-free option'],
    ingredients: [
      { item: 'Cod fillet', amount: '300 g', brand: { REWE: 'REWE Beste Wahl Kabeljau', Edeka: 'EDEKA Kabeljaufilet', Alnatura: 'followfish Kabeljau' } },
      { item: 'Cultured butter', amount: '40 g', brand: { REWE: 'REWE Bio Süßrahmbutter', Edeka: 'Kerrygold Butter', Alnatura: 'Alnatura Bio Butter' } },
      { item: 'Asparagus', amount: '300 g', brand: { REWE: 'REWE Bio Grünspargel', Edeka: 'Edeka Grünspargel', Alnatura: 'Alnatura Grünspargel' } },
      { item: 'Spinach', amount: '200 g', brand: { REWE: 'REWE Bio Babyspinat', Edeka: 'Edeka Bio Spinat', Alnatura: 'Alnatura Babyspinat' } },
      { item: 'Lemon', amount: '1', brand: { REWE: 'REWE Bio Zitrone', Edeka: 'Edeka Bio Zitrone', Alnatura: 'Alnatura Bio-Zitrone' } },
      { item: 'Capers', amount: '1 tbsp', brand: { REWE: 'REWE Feine Welt Kapern', Edeka: 'Edeka Kapern', Alnatura: 'Alnatura Kapern' } },
    ],
    steps: [
      'Pat the cod dry, season with sea salt. Rest 10 minutes.',
      'Brown butter in a heavy skillet until it smells nutty. Pour off into a bowl, leaving a film.',
      'Sear cod skin-side down 4 minutes; flip 2 minutes. Rest on a warm plate.',
      'In the same pan, blister asparagus 3 minutes, then wilt spinach off the heat.',
      'Plate cod over greens. Spoon brown butter, capers, a wide squeeze of lemon.',
    ],
    notes: 'The prebiotic fiber in asparagus feeds Bifidobacterium overnight — a clean insulin-flat dinner that does gut-repair work while you sleep. Zero starch keeps overnight insulin entirely flat.',
  },
  {
    id: 'r-ovu-salmon',
    title: 'Slow-Roast Salmon, Cucumber, Fennel',
    source: 'Sallys Welt',
    author: 'Sally Özcan',
    sourceUrl: 'https://sallys-blog.de/rezepte/green-secret-sauce',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?fit=crop&w=800&h=600&q=80',
    cuisine: 'nordic',
    minutes: 30,
    servings: 2,
    protein: 34,
    carbs: 12,
    fat: 24,
    meal: 'dinner',
    phases: ['ovulatory'],
    plantCount: 5,
    tags: ['Antioxidant', 'Cooling', 'Gluten-free', 'Zero starch', 'Low-FODMAP'],
    ingredients: [
      { item: 'Wild salmon', amount: '300 g', brand: { REWE: 'REWE Bio Lachsfilet', Edeka: 'followfish Lachs', Alnatura: 'followfish Lachsfilet' } },
      { item: 'Cucumber', amount: '1', brand: { REWE: 'REWE Bio Gurke', Edeka: 'Edeka Bio Salatgurke', Alnatura: 'Alnatura Salatgurke' } },
      { item: 'Fennel bulb', amount: '1', brand: { REWE: 'REWE Bio Fenchel', Edeka: 'Edeka Bio Fenchel', Alnatura: 'Alnatura Fenchel' } },
      { item: 'Greek yogurt', amount: '4 tbsp', brand: { REWE: 'REWE Bio Joghurt Griechischer Art', Edeka: 'MEVGAL Joghurt', Alnatura: 'Andechser Natur Joghurt' } },
      { item: 'Mint', amount: '½ bunch', brand: { REWE: 'REWE Bio Minze', Edeka: 'Edeka Bio Minze', Alnatura: 'Alnatura Minze' } },
    ],
    steps: [
      'Heat oven to 140°C. Rub salmon with olive oil, salt, lemon zest. Roast 22 minutes.',
      'Shave fennel and cucumber paper-thin on a mandoline. Salt lightly; drain 5 minutes.',
      'Stir yogurt with mint, lemon juice, a pinch of cumin.',
      'Plate the slow salmon; pile shaved salad alongside; spoon yogurt across the warm fish.',
    ],
    notes: 'Fennel is the ultimate carminative — it reduces bloating and spasm by relaxing smooth intestinal muscle. Mint and cucumber are classic Pitta-cooling herbs. Omega-3s in wild salmon reduce the LH-surge inflammation.',
  },
  {
    id: 'r-breakfast-eggs',
    title: 'Soft-Folded Eggs, Avocado, Sourdough Crumb',
    source: 'Kitchen Stories',
    author: 'Xueci Cheng',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/tiktoks-viral-pesto-eggs-2-ways-en',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?fit=crop&w=800&h=600&q=80',
    cuisine: 'french',
    minutes: 12,
    servings: 1,
    protein: 26,
    carbs: 18,
    fat: 28,
    meal: 'breakfast',
    phases: ['menstrual', 'follicular', 'ovulatory', 'luteal'],
    plantCount: 3,
    tags: ['Quick', 'Protein-forward', 'Glucose-blunted', 'Vegetarian'],
    ingredients: [
      { item: 'Pasture eggs', amount: '3', brand: { REWE: 'REWE Bio Eier Freiland', Edeka: 'EDEKA Bio Eier', Alnatura: 'Alnatura Bio Eier' } },
      { item: 'Avocado', amount: '½', brand: { REWE: 'REWE Bio Avocado', Edeka: 'Edeka Bio Avocado', Alnatura: 'Alnatura Avocado' } },
      { item: 'Sourdough', amount: '1 slice', brand: { REWE: 'REWE Feine Welt Sauerteig', Edeka: 'Mestemacher Sauerteigbrot', Alnatura: 'Alnatura Sauerteigbrot' } },
      { item: 'Cultured butter', amount: '15 g', brand: { REWE: 'REWE Bio Süßrahmbutter', Edeka: 'Kerrygold Butter', Alnatura: 'Alnatura Bio Butter' } },
      { item: 'Chili flakes', amount: '½ tsp', brand: { REWE: 'Just Spices Chili', Edeka: 'Ankerkraut Chili', Alnatura: 'Alnatura Chiliflocken' } },
    ],
    steps: [
      'Toast the sourdough until deep gold; tear into rough crumb.',
      'Whisk eggs with sea salt. Melt butter over low heat — really low.',
      'Pour the eggs in; pull them slowly with a silicone spatula. Take them off while still wet.',
      'Slide onto a plate, fan avocado, scatter sourdough crumb and chili.',
    ],
    notes: 'Fat and protein eaten first blunts the glucose curve of any carb that follows. The avocado provides prebiotic fiber and potassium. Sourdough fermentation pre-digests some of the gluten and phytic acid.',
  },

  // ── BREAKFASTS ──────────────────────────────────────────────────────────────

  {
    id: 'r-chia-kefir-bowl',
    title: 'Kefir Chia Bowl with Wild Blueberries',
    source: 'Green Kitchen Stories',
    author: 'David Frenkiel',
    sourceUrl: 'https://greenkitchenstories.com/chia-pudding/',
    imageUrl: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?fit=crop&w=800&h=600&q=80',
    cuisine: 'nordic',
    minutes: 10,
    servings: 1,
    protein: 20,
    carbs: 34,
    fat: 13,
    meal: 'breakfast',
    phases: ['follicular', 'ovulatory'],
    plantCount: 4,
    tags: ['Probiotic', 'Gut-healing', 'Gluten-free', 'Vegetarian'],
    ingredients: [
      { item: 'Kefir', amount: '200 ml', brand: { REWE: 'Andechser Bio Kefir', Edeka: 'Söbbeke Bio Kefir', Alnatura: 'Andechser Natur Kefir' } },
      { item: 'Chia seeds', amount: '2 tbsp', brand: { REWE: 'REWE Bio Chiasamen', Edeka: 'Seeberger Chiasamen', Alnatura: 'Alnatura Chiasamen' } },
      { item: 'Frozen wild blueberries', amount: '80 g', brand: { REWE: 'REWE Bio Blaubeeren TK', Edeka: 'Edeka Bio Heidelbeeren', Alnatura: 'Alnatura Blaubeeren gefroren' } },
      { item: 'Ground flaxseed', amount: '1 tbsp', brand: { REWE: 'REWE Bio Leinsamen gemahlen', Edeka: 'Seeberger Leinsamen', Alnatura: 'Alnatura Leinsamen' } },
      { item: 'Raw honey', amount: '1 tsp', brand: { REWE: 'REWE Bio Honig', Edeka: 'Edeka Bio Honig', Alnatura: 'Alnatura Honig' } },
    ],
    steps: [
      'The night before: stir chia seeds into kefir, cover, refrigerate overnight — they absorb and swell into a thick pudding.',
      'In the morning, warm frozen blueberries in a small pan 2 minutes until they burst and run.',
      'Spoon chia pudding into a bowl. Pour warm blueberries over, scatter ground flax.',
      'Drizzle honey. Eat within 20 minutes of assembly for maximum probiotic activity.',
    ],
    notes: 'Kefir provides 12 live strains of Lactobacillus — the Estrobolome\'s direct food. Wild blueberry anthocyanins are among the most potent microbiome-supporting antioxidants measured in human trials. Chia is 40% dietary fiber, mainly soluble, which slows glucose absorption dramatically.',
  },

  {
    id: 'r-golden-oats',
    title: 'Golden Milk Overnight Oats',
    source: 'Minimalist Baker',
    author: 'Dana Shultz',
    sourceUrl: 'https://minimalistbaker.com/golden-milk-overnight-oats/',
    imageUrl: 'https://images.unsplash.com/photo-1490474504059-bf2db5ab2348?fit=crop&w=800&h=600&q=80',
    cuisine: 'south-asian',
    minutes: 10,
    servings: 1,
    protein: 18,
    carbs: 46,
    fat: 20,
    meal: 'breakfast',
    phases: ['menstrual', 'luteal'],
    plantCount: 5,
    tags: ['Ayurvedic-spiced', 'Warming', 'Gluten-free', 'Vegan', 'Magnesium-rich'],
    ingredients: [
      { item: 'Rolled oats', amount: '60 g', brand: { REWE: 'REWE Bio Haferflocken', Edeka: 'Edeka Bio Zartblatt-Haferflocken', Alnatura: 'Alnatura Haferflocken' } },
      { item: 'Coconut milk', amount: '150 ml', brand: { REWE: 'REWE Bio Kokosmilch', Edeka: 'Edeka Bio Kokosmilch', Alnatura: 'Alnatura Kokosmilch' } },
      { item: 'Turmeric', amount: '½ tsp', brand: { REWE: 'REWE Bio Kurkuma', Edeka: 'Ankerkraut Kurkuma', Alnatura: 'Alnatura Bio Kurkuma' } },
      { item: 'Cinnamon', amount: '½ tsp', brand: { REWE: 'REWE Bio Zimt', Edeka: 'Ankerkraut Ceylon-Zimt', Alnatura: 'Alnatura Ceylon Zimt' } },
      { item: 'Pumpkin seeds', amount: '2 tbsp', brand: { REWE: 'REWE Bio Kürbiskerne', Edeka: 'Seeberger Kürbiskerne', Alnatura: 'Alnatura Kürbiskerne' } },
    ],
    steps: [
      'Whisk oats, coconut milk, turmeric, cinnamon, a pinch of black pepper (activates curcumin), and a pinch of salt.',
      'Cover and refrigerate overnight.',
      'In the morning, stir and thin with a splash of water if needed.',
      'Top with pumpkin seeds. Eat cool or gently warm in a small pan.',
    ],
    notes: 'Cinnamon is one of the most clinically validated blood sugar regulators — 1–3 g/day reduces fasting glucose in IR. Turmeric\'s curcumin is anti-inflammatory but poorly absorbed without black pepper (piperine increases absorption 2000%). Pumpkin seeds are the richest food source of magnesium after raw cacao.',
  },

  {
    id: 'r-salmon-rye-board',
    title: 'Smoked Salmon & Dill Rye Board',
    source: 'Sallys Welt',
    author: 'Sally Özcan',
    sourceUrl: 'https://sallys-blog.de/rezepte/lachs-brot/',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?fit=crop&w=800&h=600&q=80',
    cuisine: 'nordic',
    minutes: 8,
    servings: 1,
    protein: 30,
    carbs: 16,
    fat: 18,
    meal: 'breakfast',
    phases: ['follicular', 'ovulatory'],
    plantCount: 3,
    tags: ['Protein-forward', 'Omega-3', 'Quick', 'Glucose-blunted'],
    ingredients: [
      { item: 'Smoked salmon', amount: '100 g', brand: { REWE: 'followfish Räucherlachs', Edeka: 'EDEKA Alaska-Räucherlachs', Alnatura: 'followfish Räucherlachs' } },
      { item: 'Dark rye crispbread', amount: '2 slices', brand: { REWE: 'Wasa Knäckebrot Dunkel', Edeka: 'Mestemacher Vollkornknäcke', Alnatura: 'Alnatura Roggenknäcke' } },
      { item: 'Quark', amount: '3 tbsp', brand: { REWE: 'REWE Bio Magerquark', Edeka: 'Söbbeke Bio Quark', Alnatura: 'Andechser Natur Quark' } },
      { item: 'Dill', amount: '½ bunch', brand: { REWE: 'REWE Bio Dill', Edeka: 'Edeka Bio Dill', Alnatura: 'Alnatura Dill' } },
      { item: 'Capers', amount: '1 tbsp', brand: { REWE: 'REWE Feine Welt Kapern', Edeka: 'Edeka Kapern', Alnatura: 'Alnatura Kapern' } },
    ],
    steps: [
      'Spread quark generously over each rye crispbread.',
      'Fold smoked salmon loosely over the top.',
      'Scatter capers and dill. A squeeze of lemon if you have one.',
    ],
    notes: 'Rye has one of the lowest glycemic indexes of any grain — the dense cell wall structure means starch is digested 30% more slowly than wheat. Wild-caught salmon is the highest dietary source of EPA and DHA, which reduce the inflammatory surge around ovulation.',
  },

  {
    id: 'r-miso-egg-bowl',
    title: 'Savory Miso Egg & Mushroom Bowl',
    source: 'Kitchen Stories',
    author: 'Verena Löffler',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/tamago-gohan-japanese-egg-rice',
    imageUrl: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?fit=crop&w=800&h=600&q=80',
    cuisine: 'east-asian',
    minutes: 15,
    servings: 1,
    protein: 26,
    carbs: 24,
    fat: 16,
    meal: 'breakfast',
    phases: ['menstrual', 'follicular', 'ovulatory', 'luteal'],
    plantCount: 4,
    tags: ['Probiotic', 'Gut-healing', 'Warming', 'Umami'],
    ingredients: [
      { item: 'Pasture eggs', amount: '2', brand: { REWE: 'REWE Bio Eier Freiland', Edeka: 'EDEKA Bio Eier', Alnatura: 'Alnatura Bio Eier' } },
      { item: 'White miso paste', amount: '1 tbsp', brand: { REWE: 'REWE Bio Miso hell', Edeka: 'Edeka Asia Misopaste', Alnatura: 'Alnatura Miso hell' } },
      { item: 'Shiitake mushrooms', amount: '80 g', brand: { REWE: 'REWE Bio Shiitake', Edeka: 'Edeka Bio Shiitake', Alnatura: 'Alnatura Shiitake getrocknet' } },
      { item: 'Spring onion', amount: '2 stalks', brand: { REWE: 'REWE Bio Frühlingszwiebeln', Edeka: 'Edeka Bio Frühlingszwiebeln', Alnatura: 'Alnatura Frühlingszwiebeln' } },
      { item: 'Sesame oil', amount: '1 tsp', brand: { REWE: 'REWE Feine Welt Sesamöl', Edeka: 'Edeka Asia Sesamöl', Alnatura: 'Alnatura Sesamöl geröstet' } },
    ],
    steps: [
      'Sauté shiitake in a dry pan 3 minutes until edges brown. Set aside.',
      'Whisk eggs with miso paste — no extra salt needed.',
      'Scramble low and slow in a little sesame oil until barely set.',
      'Bowl up: eggs, mushrooms, sliced spring onion, a final drop of sesame oil.',
    ],
    notes: 'White miso is a live fermented food — it should never boil. Whisk into eggs off the heat. Shiitake contains lentinan, a beta-glucan that directly stimulates Natural Killer cell activity. Eggs provide all 9 essential amino acids plus the highest dietary source of choline for liver health.',
  },

  {
    id: 'r-buckwheat-pancakes',
    title: 'Buckwheat Blinis with Yogurt & Berries',
    source: 'REWE Rezepte',
    author: 'REWE Küche',
    sourceUrl: 'https://www.rewe.de/rezepte/buchweizen-pfannkuchen/',
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?fit=crop&w=800&h=600&q=80',
    cuisine: 'german',
    minutes: 20,
    servings: 2,
    protein: 22,
    carbs: 40,
    fat: 12,
    meal: 'breakfast',
    phases: ['follicular', 'ovulatory'],
    plantCount: 4,
    tags: ['Gluten-free', 'Vegetarian', 'Estrobolome', 'Antioxidant'],
    ingredients: [
      { item: 'Buckwheat flour', amount: '100 g', brand: { REWE: 'REWE Bio Buchweizenmehl', Edeka: 'Edeka Bio Buchweizenmehl', Alnatura: 'Alnatura Buchweizenmehl' } },
      { item: 'Pasture eggs', amount: '2', brand: { REWE: 'REWE Bio Eier Freiland', Edeka: 'EDEKA Bio Eier', Alnatura: 'Alnatura Bio Eier' } },
      { item: 'Kefir', amount: '150 ml', brand: { REWE: 'Andechser Bio Kefir', Edeka: 'Söbbeke Bio Kefir', Alnatura: 'Andechser Natur Kefir' } },
      { item: 'Mixed berries', amount: '100 g', brand: { REWE: 'REWE Bio Beerenmix TK', Edeka: 'Edeka Bio Beerenmix', Alnatura: 'Alnatura Waldbeeren' } },
      { item: 'Greek yogurt', amount: '4 tbsp', brand: { REWE: 'REWE Bio Joghurt Griechischer Art', Edeka: 'MEVGAL Griechischer Joghurt', Alnatura: 'Andechser Natur Joghurt' } },
    ],
    steps: [
      'Whisk buckwheat flour, eggs, kefir, and a pinch of salt to a smooth thin batter.',
      'Rest 10 minutes while a nonstick pan heats over medium-low.',
      'Cook small blinis (~8 cm) in a dry pan, 2 min per side, until bubbles form and set.',
      'Serve warm with yogurt and berries. A drizzle of honey is optional.',
    ],
    notes: 'Buckwheat is botanically a seed — completely gluten-free and rich in rutin, a flavonoid that strengthens capillary walls and has direct anti-estrogenic effects via aromatase inhibition. Kefir in the batter adds probiotic cultures and lactic acid, which partially breaks down the phytic acid in the flour.',
  },

  // ── LUNCHES ─────────────────────────────────────────────────────────────────

  {
    id: 'r-roast-chicken-fennel',
    title: 'Roast Chicken Thighs & Fennel',
    source: 'Kitchen Stories',
    author: 'Ruby Goss',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/baked-chicken-thighs-with-fennel-and-tomatoes',
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?fit=crop&w=800&h=600&q=80',
    cuisine: 'mediterranean',
    minutes: 45,
    servings: 2,
    protein: 40,
    carbs: 10,
    fat: 24,
    meal: 'lunch',
    phases: ['follicular', 'ovulatory', 'luteal'],
    plantCount: 4,
    tags: ['Gluten-free', 'Low-FODMAP', 'Dairy-free option', 'Protein-forward'],
    ingredients: [
      { item: 'Chicken thighs skin-on', amount: '4 pieces', brand: { REWE: 'REWE Bio Hähnchenschenkel', Edeka: 'Edeka Bio Hähnchenschenkel', Alnatura: 'Alnatura Bio Hähnchen' } },
      { item: 'Fennel bulb', amount: '2', brand: { REWE: 'REWE Bio Fenchel', Edeka: 'Edeka Bio Fenchel', Alnatura: 'Alnatura Fenchel' } },
      { item: 'Cherry tomatoes', amount: '200 g', brand: { REWE: 'REWE Bio Kirschtomaten', Edeka: 'Edeka Bio Kirschtomaten', Alnatura: 'Alnatura Kirschtomaten' } },
      { item: 'Extra virgin olive oil', amount: '3 tbsp', brand: { REWE: 'REWE Bio Olivenöl Nativ Extra', Edeka: 'BIO WERTKOST Olivenöl', Alnatura: 'Alnatura Olivenöl Nativ Extra' } },
      { item: 'Lemon', amount: '1', brand: { REWE: 'REWE Bio Zitrone', Edeka: 'Edeka Bio Zitrone', Alnatura: 'Alnatura Bio-Zitrone' } },
    ],
    steps: [
      'Heat oven to 210°C. Season chicken thighs aggressively with salt and pepper.',
      'Quarter fennel lengthways. Toss with cherry tomatoes, olive oil, lemon zest, and a crack of pepper in a large roasting tin.',
      'Nestle chicken skin-side up over the veg. Roast 35–38 minutes until skin is lacquered and amber.',
      'Rest 5 minutes. Squeeze lemon over everything before serving.',
    ],
    notes: 'Chicken thighs contain significantly more zinc and iron than breast — both critical minerals for thyroid function and cycle regulation. Fennel\'s anethole is a phytoestrogen that gently supports estrogen activity in the follicular phase without the synthetic load.',
  },

  {
    id: 'r-red-lentil-soup',
    title: 'Red Lentil & Smoked Paprika Soup',
    source: 'Sallys Welt',
    author: 'Sally Özcan',
    sourceUrl: 'https://sallys-blog.de/rezepte/rote-linsensuppe/',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?fit=crop&w=800&h=600&q=80',
    cuisine: 'south-asian',
    minutes: 30,
    servings: 2,
    protein: 24,
    carbs: 48,
    fat: 8,
    meal: 'lunch',
    phases: ['menstrual', 'luteal'],
    plantCount: 6,
    tags: ['Ayurvedic-spiced', 'Warming', 'Gut-healing', 'Vegan', 'Gluten-free'],
    ingredients: [
      { item: 'Red lentils', amount: '180 g', brand: { REWE: 'REWE Bio Rote Linsen', Edeka: 'Edeka Bio Rote Linsen', Alnatura: 'Alnatura Rote Linsen' } },
      { item: 'Carrot', amount: '2', brand: { REWE: 'REWE Bio Karotten', Edeka: 'Edeka Bio Karotten', Alnatura: 'Alnatura Karotten' } },
      { item: 'Smoked paprika', amount: '2 tsp', brand: { REWE: 'Just Spices Paprika geräuchert', Edeka: 'Ankerkraut Paprika geräuchert', Alnatura: 'Alnatura Paprika edelsüß' } },
      { item: 'Cumin seeds', amount: '1 tsp', brand: { REWE: 'REWE Bio Kreuzkümmel', Edeka: 'Edeka Kreuzkümmel', Alnatura: 'Alnatura Kreuzkümmel' } },
      { item: 'Fresh ginger', amount: '10 g', brand: { REWE: 'REWE Bio Ingwer', Edeka: 'Edeka Bio Ingwer', Alnatura: 'Alnatura Ingwer' } },
      { item: 'Coconut milk', amount: '80 ml', brand: { REWE: 'REWE Bio Kokosmilch', Edeka: 'Edeka Bio Kokosmilch', Alnatura: 'Alnatura Kokosmilch' } },
    ],
    steps: [
      'Bloom cumin seeds in a dry pot 30 seconds. Add ginger, paprika, stir 20 seconds.',
      'Add lentils, diced carrot, and 900 ml water. Bring to a boil, skim.',
      'Simmer covered 22 minutes until lentils collapse completely.',
      'Stir in coconut milk. Blend half for a half-smooth texture. Season generously.',
    ],
    notes: 'Red lentils dissolve into soup without soaking — their cell walls rupture on boiling, releasing resistant starch that feeds Bifidobacterium. Smoked paprika contains capsaicin which accelerates gastric emptying and improves intestinal motility — exactly what\'s needed in the slow-motility luteal phase.',
  },

  {
    id: 'r-nicoise-salad',
    title: 'Niçoise with Seared Tuna & Soft Egg',
    source: 'Kitchen Stories',
    author: 'Xueci Cheng',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/classic-nicoise-salad',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?fit=crop&w=800&h=600&q=80',
    cuisine: 'french',
    minutes: 22,
    servings: 2,
    protein: 36,
    carbs: 14,
    fat: 22,
    meal: 'lunch',
    phases: ['follicular', 'ovulatory'],
    plantCount: 6,
    tags: ['Gluten-free', 'Low-FODMAP', 'Protein-forward', 'Antioxidant'],
    ingredients: [
      { item: 'Tuna steak', amount: '250 g', brand: { REWE: 'REWE Beste Wahl Thunfisch', Edeka: 'followfish Thunfisch', Alnatura: 'followfish Thunfisch' } },
      { item: 'Fine green beans', amount: '200 g', brand: { REWE: 'REWE Bio Grüne Bohnen', Edeka: 'Edeka Bio Grüne Bohnen', Alnatura: 'Alnatura Grüne Bohnen' } },
      { item: 'Pasture eggs', amount: '2', brand: { REWE: 'REWE Bio Eier Freiland', Edeka: 'EDEKA Bio Eier', Alnatura: 'Alnatura Bio Eier' } },
      { item: 'Cherry tomatoes', amount: '150 g', brand: { REWE: 'REWE Bio Kirschtomaten', Edeka: 'Edeka Bio Kirschtomaten', Alnatura: 'Alnatura Kirschtomaten' } },
      { item: 'Kalamata olives', amount: '40 g', brand: { REWE: 'REWE Feine Welt Kalamata-Oliven', Edeka: 'Edeka Kalamata-Oliven', Alnatura: 'Alnatura Oliven schwarz' } },
    ],
    steps: [
      'Soft-boil eggs 6½ minutes. Blanch green beans 3 minutes. Both go into ice water.',
      'Season tuna steak generously. Sear in a very hot dry pan 90 seconds per side — stay rare inside.',
      'Whisk 2 tbsp olive oil, 1 tsp Dijon, lemon juice, salt into a dressing.',
      'Arrange beans, halved tomatoes, olives, peeled halved eggs. Slice tuna over the top. Dress everything.',
    ],
    notes: 'Omega-3 from tuna reduces the LH-surge inflammation at ovulation. Olives contain oleic acid and oleuropein — a polyphenol that directly stimulates the growth of beneficial Bifidobacterium and Lactobacillus strains in the Estrobolome.',
  },

  {
    id: 'r-pumpkin-bisque',
    title: 'Kabocha Bisque with Toasted Pepitas',
    source: 'Alnatura Magazin',
    author: 'Alnatura Redaktion',
    sourceUrl: 'https://www.alnatura.de/de-de/rezepte/kuerbissuppe/',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?fit=crop&w=800&h=600&q=80',
    cuisine: 'south-asian',
    minutes: 35,
    servings: 2,
    protein: 12,
    carbs: 44,
    fat: 20,
    meal: 'lunch',
    phases: ['menstrual', 'luteal'],
    plantCount: 5,
    tags: ['Ayurvedic-spiced', 'Warming', 'Vegan', 'Gluten-free', 'Seasonal', 'Magnesium-rich'],
    ingredients: [
      { item: 'Kabocha squash', amount: '1 kg', brand: { REWE: 'REWE Bio Hokkaido-Kürbis', Edeka: 'Edeka Bio Kürbis', Alnatura: 'Alnatura Hokkaido-Kürbis' } },
      { item: 'Coconut milk', amount: '200 ml', brand: { REWE: 'REWE Bio Kokosmilch', Edeka: 'Edeka Bio Kokosmilch', Alnatura: 'Alnatura Kokosmilch' } },
      { item: 'Fresh ginger', amount: '20 g', brand: { REWE: 'REWE Bio Ingwer', Edeka: 'Edeka Bio Ingwer', Alnatura: 'Alnatura Ingwer' } },
      { item: 'Cinnamon', amount: '½ tsp', brand: { REWE: 'REWE Bio Zimt', Edeka: 'Ankerkraut Ceylon-Zimt', Alnatura: 'Alnatura Ceylon Zimt' } },
      { item: 'Pumpkin seeds', amount: '3 tbsp', brand: { REWE: 'REWE Bio Kürbiskerne', Edeka: 'Seeberger Kürbiskerne', Alnatura: 'Alnatura Kürbiskerne' } },
    ],
    steps: [
      'Roast squash halves cut-side down at 200°C for 30 minutes. Scoop flesh.',
      'Blend squash flesh with ginger, cinnamon, coconut milk, and 400 ml water until completely smooth.',
      'Pour into a pot, warm gently, adjust seasoning.',
      'Toast pumpkin seeds in a dry pan 2 minutes. Scatter over and serve with a swirl of coconut milk.',
    ],
    notes: 'Kabocha is one of the richest dietary sources of beta-carotene — a precursor to Vitamin A, which is essential for mucus production in the gut lining. Pumpkin seeds contain more magnesium per gram than any food except raw cacao — magnesium is the single most depleted mineral in the luteal phase.',
  },

  {
    id: 'r-falafel-plate',
    title: 'Baked Falafel & Tabbouleh Plate',
    source: 'REWE Rezepte',
    author: 'REWE Küche',
    sourceUrl: 'https://www.rewe.de/rezepte/falafel-mit-tabbouleh/',
    imageUrl: 'https://images.unsplash.com/photo-1564671165093-20688ff1fffa?fit=crop&w=800&h=600&q=80',
    cuisine: 'middle-east',
    minutes: 35,
    servings: 2,
    protein: 22,
    carbs: 52,
    fat: 18,
    meal: 'lunch',
    phases: ['follicular'],
    plantCount: 8,
    tags: ['Estrobolome', 'Gut-healing', 'Vegan', 'Gluten-free option', 'Antioxidant'],
    ingredients: [
      { item: 'Cooked chickpeas', amount: '400 g', brand: { REWE: 'REWE Bio Kichererbsen', Edeka: 'Edeka Bio Kichererbsen', Alnatura: 'Alnatura Kichererbsen' } },
      { item: 'Fresh parsley', amount: '1 bunch', brand: { REWE: 'REWE Bio Petersilie', Edeka: 'Edeka Bio Petersilie', Alnatura: 'Alnatura Petersilie' } },
      { item: 'Quinoa', amount: '80 g', brand: { REWE: 'REWE Bio Quinoa', Edeka: 'Edeka Bio Quinoa', Alnatura: 'Alnatura Quinoa' } },
      { item: 'Tahini', amount: '3 tbsp', brand: { REWE: 'REWE Bio Tahini', Edeka: 'Bio Sesammus', Alnatura: 'Alnatura Sesammus' } },
      { item: 'Lemon', amount: '2', brand: { REWE: 'REWE Bio Zitrone', Edeka: 'Edeka Bio Zitrone', Alnatura: 'Alnatura Bio-Zitrone' } },
      { item: 'Fresh mint', amount: '½ bunch', brand: { REWE: 'REWE Bio Minze', Edeka: 'Edeka Bio Minze', Alnatura: 'Alnatura Minze' } },
    ],
    steps: [
      'Pulse chickpeas with parsley, cumin, salt to a rough paste. Shape into patties and bake 220°C for 20 min.',
      'Cook quinoa per packet. Cool to room temperature.',
      'Toss quinoa with chopped parsley, mint, lemon juice, olive oil.',
      'Thin tahini with lemon and water to a dressing. Plate falafel over tabbouleh, drizzle tahini.',
    ],
    notes: 'Chickpeas contain raffinose-family oligosaccharides — the prebiotic fiber that Bifidobacterium preferentially ferments. Parsley is extremely high in apigenin, a flavonoid with direct aromatase-inhibiting activity that helps the Estrobolome clear estrogen in the follicular phase.',
  },

  {
    id: 'r-mackerel-board',
    title: 'Smoked Mackerel & Sauerkraut Rye',
    source: 'Kitchen Stories',
    author: 'Hanna Reder',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/open-faced-smoked-fish-sandwich',
    imageUrl: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?fit=crop&w=800&h=600&q=80',
    cuisine: 'nordic',
    minutes: 10,
    servings: 1,
    protein: 34,
    carbs: 18,
    fat: 26,
    meal: 'lunch',
    phases: ['menstrual', 'follicular', 'ovulatory', 'luteal'],
    plantCount: 3,
    tags: ['Probiotic', 'Fermented', 'Gut-healing', 'Omega-3', 'Quick'],
    ingredients: [
      { item: 'Smoked mackerel fillet', amount: '150 g', brand: { REWE: 'REWE Beste Wahl Makrelenfilet', Edeka: 'EDEKA Räuchermakrele', Alnatura: 'followfish Makrele' } },
      { item: 'Dark rye bread', amount: '2 slices', brand: { REWE: 'REWE Bio Roggenbrot', Edeka: 'Mestemacher Roggenvollkornbrot', Alnatura: 'Alnatura Roggenbrot' } },
      { item: 'Sauerkraut', amount: '4 tbsp', brand: { REWE: 'Hengstenberg Sauerkraut', Edeka: 'Mildessa Sauerkraut', Alnatura: 'Alnatura Sauerkraut' } },
      { item: 'Horseradish cream', amount: '2 tbsp', brand: { REWE: 'REWE Meerrettichcreme', Edeka: 'Edeka Meerrettich', Alnatura: 'Alnatura Meerrettich' } },
      { item: 'Dill', amount: '¼ bunch', brand: { REWE: 'REWE Bio Dill', Edeka: 'Edeka Bio Dill', Alnatura: 'Alnatura Dill' } },
    ],
    steps: [
      'Spread horseradish cream generously over the rye.',
      'Flake mackerel in large pieces over the top.',
      'Pile sauerkraut alongside. Finish with dill.',
    ],
    notes: 'This is a Nordic gut-health triple play: fermented rye (sourdough lactic acid bacteria), sauerkraut (Leuconostoc and Lactobacillus), and mackerel omega-3 that reduce intestinal inflammation. Mackerel has nearly double the omega-3 of salmon per gram and is more sustainable.',
  },

  {
    id: 'r-beet-goat-cheese',
    title: 'Roasted Beet, Walnut & Goat Cheese',
    source: 'Alnatura Magazin',
    author: 'Alnatura Redaktion',
    sourceUrl: 'https://www.alnatura.de/de-de/rezepte/rote-bete-salat-mit-ziegenkase/',
    imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?fit=crop&w=800&h=600&q=80',
    cuisine: 'mediterranean',
    minutes: 40,
    servings: 2,
    protein: 20,
    carbs: 30,
    fat: 28,
    meal: 'lunch',
    phases: ['follicular', 'ovulatory'],
    plantCount: 6,
    tags: ['Estrobolome', 'Gluten-free', 'Vegetarian', 'Seasonal', 'Antioxidant'],
    ingredients: [
      { item: 'Roasted beets', amount: '4 medium', brand: { REWE: 'REWE Bio Rote Bete vorgegart', Edeka: 'Edeka Bio Rote Bete', Alnatura: 'Alnatura Rote Bete gegart' } },
      { item: 'Soft goat cheese', amount: '120 g', brand: { REWE: 'REWE Bio Ziegenkäse', Edeka: 'Edeka Ziegenfrischkäse', Alnatura: 'Alnatura Ziegenkäse' } },
      { item: 'Walnuts', amount: '40 g', brand: { REWE: 'REWE Bio Walnüsse', Edeka: 'Seeberger Walnüsse', Alnatura: 'Alnatura Walnüsse' } },
      { item: 'Rocket', amount: '80 g', brand: { REWE: 'REWE Bio Rucola', Edeka: 'Edeka Bio Rucola', Alnatura: 'Alnatura Rucola' } },
      { item: 'Balsamic vinegar', amount: '2 tbsp', brand: { REWE: 'REWE Feine Welt Balsamico', Edeka: 'Edeka Balsamessig', Alnatura: 'Alnatura Balsamessig' } },
    ],
    steps: [
      'Halve or quarter beets. Toss with olive oil, roast at 200°C for 25 min (skip if using pre-cooked).',
      'Toast walnuts in a dry pan 4 minutes until fragrant.',
      'Arrange rocket on plates. Add beets, crumble goat cheese over.',
      'Scatter walnuts. Dress with balsamic and a good pour of olive oil.',
    ],
    notes: 'Beetroot\'s betaine is one of the most important methyl donors in liver estrogen detoxification — it directly supports the Phase II liver enzymes that conjugate and deactivate estrogen for bowel excretion. Walnuts are the richest plant source of ALA omega-3 and also contain ellagitannins that the gut converts to urolithin A.',
  },

  {
    id: 'r-chickpea-stew',
    title: 'Mediterranean Chickpea & Spinach Stew',
    source: 'REWE Rezepte',
    author: 'REWE Küche',
    sourceUrl: 'https://www.rewe.de/rezepte/kichererbsen-spinat-eintopf/',
    imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?fit=crop&w=800&h=600&q=80',
    cuisine: 'mediterranean',
    minutes: 25,
    servings: 2,
    protein: 22,
    carbs: 46,
    fat: 16,
    meal: 'lunch',
    phases: ['follicular', 'luteal'],
    plantCount: 7,
    tags: ['Estrobolome', 'Gut-healing', 'Gluten-free', 'Vegetarian', 'Magnesium-rich'],
    ingredients: [
      { item: 'Cooked chickpeas', amount: '400 g', brand: { REWE: 'REWE Bio Kichererbsen', Edeka: 'Edeka Bio Kichererbsen', Alnatura: 'Alnatura Kichererbsen' } },
      { item: 'Baby spinach', amount: '150 g', brand: { REWE: 'REWE Bio Babyspinat', Edeka: 'Edeka Bio Spinat', Alnatura: 'Alnatura Babyspinat' } },
      { item: 'Crushed tomatoes', amount: '400 g', brand: { REWE: 'REWE Bio Tomaten gehackt', Edeka: 'Edeka Bio Tomaten', Alnatura: 'Alnatura Tomaten gehackt' } },
      { item: 'Cumin seeds', amount: '1 tsp', brand: { REWE: 'REWE Bio Kreuzkümmel', Edeka: 'Edeka Kreuzkümmel', Alnatura: 'Alnatura Kreuzkümmel' } },
      { item: 'Feta cheese', amount: '80 g', brand: { REWE: 'REWE Bio Feta', Edeka: 'Dodoni Feta', Alnatura: 'Alnatura Feta' } },
      { item: 'Extra virgin olive oil', amount: '2 tbsp', brand: { REWE: 'REWE Bio Olivenöl Nativ Extra', Edeka: 'BIO WERTKOST Olivenöl', Alnatura: 'Alnatura Olivenöl Nativ Extra' } },
    ],
    steps: [
      'Bloom cumin in olive oil 30 seconds. Add tomatoes, simmer 10 minutes until thickened.',
      'Add chickpeas, stir, simmer 8 minutes.',
      'Fold in spinach off the heat until wilted.',
      'Crumble feta over. A squeeze of lemon finishes it.',
    ],
    notes: 'Spinach is the highest dietary source of magnesium by volume — critical in luteal phase for smooth muscle relaxation and reducing progesterone-driven constipation. Tomato lycopene is fat-soluble; it absorbs 4× better when cooked with olive oil, as in this recipe.',
  },

  // ── DINNERS ──────────────────────────────────────────────────────────────────

  {
    id: 'r-chicken-braised-kale',
    title: 'Slow-Cooked Chicken & Braised Cavolo',
    source: 'Kitchen Stories',
    author: 'Ruby Goss',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/braised-chicken-legs-with-kale',
    imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?fit=crop&w=800&h=600&q=80',
    cuisine: 'mediterranean',
    minutes: 50,
    servings: 2,
    protein: 40,
    carbs: 8,
    fat: 22,
    meal: 'dinner',
    phases: ['menstrual', 'follicular', 'ovulatory', 'luteal'],
    plantCount: 4,
    tags: ['Zero starch', 'Gluten-free', 'Low-FODMAP', 'Dairy-free'],
    ingredients: [
      { item: 'Chicken legs', amount: '4 pieces', brand: { REWE: 'REWE Bio Hähnchenkeulen', Edeka: 'Edeka Bio Hähnchenkeulen', Alnatura: 'Alnatura Bio Hähnchen' } },
      { item: 'Lacinato kale', amount: '1 bunch', brand: { REWE: 'REWE Bio Schwarzkohl', Edeka: 'Edeka Bio Grünkohl', Alnatura: 'Alnatura Grünkohl' } },
      { item: 'Lemon', amount: '1', brand: { REWE: 'REWE Bio Zitrone', Edeka: 'Edeka Bio Zitrone', Alnatura: 'Alnatura Bio-Zitrone' } },
      { item: 'Extra virgin olive oil', amount: '3 tbsp', brand: { REWE: 'REWE Bio Olivenöl Nativ Extra', Edeka: 'BIO WERTKOST Olivenöl', Alnatura: 'Alnatura Olivenöl Nativ Extra' } },
      { item: 'Capers', amount: '2 tbsp', brand: { REWE: 'REWE Feine Welt Kapern', Edeka: 'Edeka Kapern', Alnatura: 'Alnatura Kapern' } },
    ],
    steps: [
      'Season chicken. Brown all over in olive oil in a wide oven dish, 8 min.',
      'Deglaze with a splash of water and lemon juice. Cover tightly, braise in 170°C oven 35 minutes.',
      'Meanwhile, blanch kale 3 minutes in salted water. Drain and squeeze dry.',
      'Toss kale in the braising juices with capers. Serve chicken over the greens with lemon zest.',
    ],
    notes: 'Cavolo nero (lacinato kale) contains the highest concentration of sulforaphane precursors of any commonly available vegetable. Sulforaphane is the compound that directly upregulates Phase II liver enzymes — the same enzymes that determine how efficiently your body deactivates and excretes used estrogen.',
  },

  {
    id: 'r-lamb-kofta',
    title: 'Lamb Kofta, Cucumber Yogurt, Sumac',
    source: 'Edeka Rezepte',
    author: 'Edeka Küche',
    sourceUrl: 'https://www.edeka.de/rezepte/fleisch-geflugel/lammhackbaellchen/',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?fit=crop&w=800&h=600&q=80',
    cuisine: 'middle-east',
    minutes: 30,
    servings: 2,
    protein: 38,
    carbs: 10,
    fat: 28,
    meal: 'dinner',
    phases: ['menstrual', 'luteal'],
    plantCount: 5,
    tags: ['Ayurvedic-spiced', 'Zero starch', 'Warming', 'Gluten-free'],
    ingredients: [
      { item: 'Ground lamb', amount: '400 g', brand: { REWE: 'REWE Bio Lammhack', Edeka: 'Edeka Bio Lammhack', Alnatura: 'Alnatura Bio Lammfleisch' } },
      { item: 'Cumin seeds', amount: '1 tsp', brand: { REWE: 'REWE Bio Kreuzkümmel', Edeka: 'Edeka Kreuzkümmel', Alnatura: 'Alnatura Kreuzkümmel' } },
      { item: 'Sumac', amount: '1 tsp', brand: { REWE: 'Just Spices Sumach', Edeka: 'Ankerkraut Sumach', Alnatura: 'Alnatura Sumach' } },
      { item: 'Greek yogurt', amount: '150 g', brand: { REWE: 'REWE Bio Joghurt Griechischer Art', Edeka: 'MEVGAL Griechischer Joghurt', Alnatura: 'Andechser Natur Joghurt' } },
      { item: 'Cucumber', amount: '½', brand: { REWE: 'REWE Bio Gurke', Edeka: 'Edeka Bio Salatgurke', Alnatura: 'Alnatura Salatgurke' } },
    ],
    steps: [
      'Mix lamb with cumin, a pinch of cinnamon, salt, and pepper. Shape into 8 oval kofta.',
      'Grill in a hot cast-iron pan 3 min per side until well browned and just cooked through.',
      'Grate cucumber into yogurt, squeeze out excess water, add sumac and a pinch of salt.',
      'Plate kofta on the yogurt. Scatter sumac and fresh mint leaves.',
    ],
    notes: 'Lamb is the richest red meat source of L-carnitine, which facilitates fatty acid oxidation — important for insulin signaling. The lactic acid bacteria in Greek yogurt plus the cucumber prebiotic fiber make the tzatziki a gut health unit in itself. Sumac\'s tannic acid delays gastric emptying, gently blunting the glucose curve.',
  },

  {
    id: 'r-miso-pollock',
    title: 'Miso-Glazed Pollock, Bok Choy',
    source: 'Kitchen Stories',
    author: 'Verena Löffler',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/miso-glazed-cod',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?fit=crop&w=800&h=600&q=80',
    cuisine: 'east-asian',
    minutes: 25,
    servings: 2,
    protein: 36,
    carbs: 12,
    fat: 18,
    meal: 'dinner',
    phases: ['menstrual', 'follicular', 'ovulatory', 'luteal'],
    plantCount: 3,
    tags: ['Probiotic', 'Zero starch', 'Gluten-free', 'Gut-healing'],
    ingredients: [
      { item: 'Pollock fillet', amount: '350 g', brand: { REWE: 'REWE Beste Wahl Seelachsfilet', Edeka: 'EDEKA Seelachsfilet', Alnatura: 'followfish Seelachs' } },
      { item: 'White miso paste', amount: '2 tbsp', brand: { REWE: 'REWE Bio Miso hell', Edeka: 'Edeka Asia Misopaste', Alnatura: 'Alnatura Miso hell' } },
      { item: 'Bok choy', amount: '4 heads', brand: { REWE: 'REWE Pak Choi', Edeka: 'Edeka Pak Choi', Alnatura: 'Alnatura Pak Choi' } },
      { item: 'Fresh ginger', amount: '15 g', brand: { REWE: 'REWE Bio Ingwer', Edeka: 'Edeka Bio Ingwer', Alnatura: 'Alnatura Ingwer' } },
      { item: 'Sesame oil', amount: '1 tbsp', brand: { REWE: 'REWE Feine Welt Sesamöl', Edeka: 'Edeka Asia Sesamöl', Alnatura: 'Alnatura Sesamöl geröstet' } },
    ],
    steps: [
      'Mix miso with grated ginger and a tsp of sesame oil into a thin paste.',
      'Spread miso paste over fish. Marinate 15 minutes minimum, or overnight.',
      'Roast at 200°C for 12–14 minutes until the miso crust caramelises.',
      'Halve bok choy, sear cut-side down in sesame oil 3 minutes. Season with a splash of tamari.',
    ],
    notes: 'Miso is a live fermented food with significant Aspergillus oryzae culture — a fungal ferment that produces unique digestive enzymes. Important: never boil miso; here it\'s used as a marinade and the oven heat is short enough that the outer surface caramelises while the interior remains partially live. Pollock is MSC-certified and has nearly identical omega-3 profile to cod at lower cost.',
  },

  {
    id: 'r-turkey-meatballs',
    title: 'Turkey Meatballs in Spinach Bone Broth',
    source: 'Sallys Welt',
    author: 'Sally Özcan',
    sourceUrl: 'https://sallys-blog.de/rezepte/fleischbaellchen-in-bruehe/',
    imageUrl: 'https://images.unsplash.com/photo-1584990347449-a5d9f800a783?fit=crop&w=800&h=600&q=80',
    cuisine: 'south-asian',
    minutes: 35,
    servings: 2,
    protein: 42,
    carbs: 6,
    fat: 16,
    meal: 'dinner',
    phases: ['menstrual', 'luteal'],
    plantCount: 3,
    tags: ['Zero starch', 'Gut-healing', 'Gluten-free', 'Warming'],
    ingredients: [
      { item: 'Ground turkey', amount: '450 g', brand: { REWE: 'REWE Bio Putenhack', Edeka: 'Edeka Bio Putenhack', Alnatura: 'Alnatura Bio Pute' } },
      { item: 'Baby spinach', amount: '150 g', brand: { REWE: 'REWE Bio Babyspinat', Edeka: 'Edeka Bio Spinat', Alnatura: 'Alnatura Babyspinat' } },
      { item: 'Bone broth', amount: '600 ml', brand: { REWE: 'REWE Knochenbrühe', Edeka: 'Edeka Fond Knochenbrühe', Alnatura: 'Alnatura Gemüsebrühe' } },
      { item: 'Fresh ginger', amount: '10 g', brand: { REWE: 'REWE Bio Ingwer', Edeka: 'Edeka Bio Ingwer', Alnatura: 'Alnatura Ingwer' } },
      { item: 'Turmeric', amount: '1 tsp', brand: { REWE: 'REWE Bio Kurkuma', Edeka: 'Edeka Kurkuma', Alnatura: 'Alnatura Bio Kurkuma' } },
    ],
    steps: [
      'Mix turkey mince with grated ginger, turmeric, salt, and pepper. Roll into 18 small meatballs.',
      'Bring bone broth to a simmer. Drop in meatballs; poach gently 12 minutes.',
      'Fold in spinach off the heat until wilted.',
      'Serve in deep bowls with a grind of black pepper and a drizzle of olive oil.',
    ],
    notes: 'Bone broth\'s glycine and proline are the two amino acids that make collagen — the primary structural protein of the gut lining. 600 ml provides approximately 10 g of gelatin-forming proteins. Turkey is higher in tryptophan than chicken — the precursor to serotonin, which governs both mood and intestinal motility via the enteric nervous system.',
  },

  {
    id: 'r-tofu-stir-fry',
    title: 'Ginger Tofu & Bok Choy Stir-fry',
    source: 'Kitchen Stories',
    author: 'Xueci Cheng',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/crispy-tofu-stir-fry',
    imageUrl: 'https://images.unsplash.com/photo-1540914124281-342587941389?fit=crop&w=800&h=600&q=80',
    cuisine: 'east-asian',
    minutes: 20,
    servings: 2,
    protein: 28,
    carbs: 14,
    fat: 18,
    meal: 'dinner',
    phases: ['follicular', 'ovulatory'],
    plantCount: 6,
    tags: ['Vegan', 'Gluten-free', 'Cooling', 'Estrobolome', 'Zero starch'],
    ingredients: [
      { item: 'Firm tofu', amount: '400 g', brand: { REWE: 'REWE Bio Tofu Natur', Edeka: 'Edeka Bio Tofu', Alnatura: 'Alnatura Tofu Natur' } },
      { item: 'Bok choy', amount: '4 heads', brand: { REWE: 'REWE Pak Choi', Edeka: 'Edeka Pak Choi', Alnatura: 'Alnatura Pak Choi' } },
      { item: 'Fresh ginger', amount: '20 g', brand: { REWE: 'REWE Bio Ingwer', Edeka: 'Edeka Bio Ingwer', Alnatura: 'Alnatura Ingwer' } },
      { item: 'Tamari', amount: '2 tbsp', brand: { REWE: 'REWE Bio Tamari', Edeka: 'Edeka Bio Tamari', Alnatura: 'Alnatura Tamari' } },
      { item: 'Sesame oil', amount: '2 tsp', brand: { REWE: 'REWE Feine Welt Sesamöl', Edeka: 'Edeka Asia Sesamöl', Alnatura: 'Alnatura Sesamöl geröstet' } },
      { item: 'Spring onion', amount: '3 stalks', brand: { REWE: 'REWE Bio Frühlingszwiebeln', Edeka: 'Edeka Bio Frühlingszwiebeln', Alnatura: 'Alnatura Frühlingszwiebeln' } },
    ],
    steps: [
      'Press tofu dry between paper towels 10 minutes. Cut into 2 cm cubes.',
      'Pan-fry tofu cubes in a splash of neutral oil until golden all over, 8 minutes total. Remove.',
      'In the same pan, stir-fry ginger and bok choy 3 minutes on high heat.',
      'Return tofu. Add tamari and sesame oil. Toss to coat. Scatter spring onion.',
    ],
    notes: 'Fermented tofu (tempeh is better, but tofu still provides isoflavones) contains genistein and daidzein — phytoestrogens that compete with synthetic xenoestrogens at receptor sites. In the follicular phase, these gently support estrogen activity without the load of endocrine-disrupting compounds.',
  },

  {
    id: 'r-sea-bass-papillote',
    title: 'Sea Bass en Papillote, Fennel & Herbs',
    source: 'Kitchen Stories',
    author: 'Ruby Goss',
    sourceUrl: 'https://www.kitchenstories.com/en/recipes/sea-bass-en-papillote',
    imageUrl: 'https://images.unsplash.com/photo-1535140728325-a4d3707eee61?fit=crop&w=800&h=600&q=80',
    cuisine: 'french',
    minutes: 25,
    servings: 2,
    protein: 38,
    carbs: 6,
    fat: 16,
    meal: 'dinner',
    phases: ['ovulatory'],
    plantCount: 4,
    tags: ['Zero starch', 'Gluten-free', 'Low-FODMAP', 'Cooling', 'Antioxidant'],
    ingredients: [
      { item: 'Sea bass fillet', amount: '2 × 180 g', brand: { REWE: 'REWE Beste Wahl Wolfsbarschfilet', Edeka: 'EDEKA Wolfsbarsch', Alnatura: 'followfish Wolfsbarsch' } },
      { item: 'Fennel bulb', amount: '1', brand: { REWE: 'REWE Bio Fenchel', Edeka: 'Edeka Bio Fenchel', Alnatura: 'Alnatura Fenchel' } },
      { item: 'Lemon', amount: '1', brand: { REWE: 'REWE Bio Zitrone', Edeka: 'Edeka Bio Zitrone', Alnatura: 'Alnatura Bio-Zitrone' } },
      { item: 'Dill', amount: '½ bunch', brand: { REWE: 'REWE Bio Dill', Edeka: 'Edeka Bio Dill', Alnatura: 'Alnatura Dill' } },
      { item: 'Extra virgin olive oil', amount: '2 tbsp', brand: { REWE: 'REWE Bio Olivenöl Nativ Extra', Edeka: 'BIO WERTKOST Olivenöl', Alnatura: 'Alnatura Olivenöl Nativ Extra' } },
    ],
    steps: [
      'Heat oven to 190°C. Shave fennel paper-thin. Slice lemon.',
      'Place each fillet on a large square of baking paper. Layer fennel and lemon slices under and over the fish.',
      'Add dill, olive oil, salt, and a crack of pepper. Fold parcels tightly.',
      'Bake 18 minutes. Open at the table — the steam carries everything.',
    ],
    notes: 'Cooking en papillote (in parchment) is the gentlest method: no browning means no advanced glycation end-products (AGEs) which drive insulin resistance. The steam keeps tissue-hydrating minerals intact. Sea bass is rich in selenium — one of the key cofactors for the deiodinase enzymes that activate thyroid hormone.',
  },

  {
    id: 'r-prawn-courgette',
    title: 'Garlic Prawn & Courgette Ribbons',
    source: 'Edeka Rezepte',
    author: 'Edeka Küche',
    sourceUrl: 'https://www.edeka.de/rezepte/fisch-meeresfruchte/garnelen-zucchini/',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?fit=crop&w=800&h=600&q=80',
    cuisine: 'mediterranean',
    minutes: 15,
    servings: 2,
    protein: 32,
    carbs: 8,
    fat: 16,
    meal: 'dinner',
    phases: ['ovulatory', 'follicular'],
    plantCount: 4,
    tags: ['Zero starch', 'Gluten-free', 'Antioxidant', 'Cooling', 'Low-FODMAP', 'Quick'],
    ingredients: [
      { item: 'Raw king prawns', amount: '350 g', brand: { REWE: 'REWE Beste Wahl Garnelen roh', Edeka: 'EDEKA Riesengarnelen', Alnatura: 'followfish Garnelen' } },
      { item: 'Courgette', amount: '2 large', brand: { REWE: 'REWE Bio Zucchini', Edeka: 'Edeka Bio Zucchini', Alnatura: 'Alnatura Zucchini' } },
      { item: 'Lemon', amount: '1', brand: { REWE: 'REWE Bio Zitrone', Edeka: 'Edeka Bio Zitrone', Alnatura: 'Alnatura Bio-Zitrone' } },
      { item: 'Extra virgin olive oil', amount: '3 tbsp', brand: { REWE: 'REWE Bio Olivenöl Nativ Extra', Edeka: 'BIO WERTKOST Olivenöl', Alnatura: 'Alnatura Olivenöl Nativ Extra' } },
      { item: 'Fresh parsley', amount: '½ bunch', brand: { REWE: 'REWE Bio Petersilie', Edeka: 'Edeka Bio Petersilie', Alnatura: 'Alnatura Petersilie' } },
    ],
    steps: [
      'Use a vegetable peeler to ribbon the courgette lengthways into wide strands.',
      'Pat prawns dry, season. Sear in very hot olive oil 90 seconds per side. Remove.',
      'Toss courgette ribbons into the same pan with the prawn juices, 1 minute max.',
      'Plate courgette, pile prawns on top, squeeze lemon, scatter parsley.',
    ],
    notes: 'Prawns are the highest dietary source of iodine among commonly eaten foods — iodine is a direct precursor to thyroid hormones T3 and T4, both of which regulate insulin sensitivity and metabolic rate. Courgette ribbons are raw — they retain their prebiotic pectin fully intact, which is lost on cooking.',
  },
];

const PLAN_BY_PHASE = {
  menstrual:  { breakfast: 'r-golden-oats',       lunch: 'r-warming-mung-dal',  dinner: 'r-turkey-meatballs' },
  follicular: { breakfast: 'r-chia-kefir-bowl',   lunch: 'r-folli-bowl',        dinner: 'r-tofu-stir-fry' },
  ovulatory:  { breakfast: 'r-salmon-rye-board',  lunch: 'r-nicoise-salad',     dinner: 'r-sea-bass-papillote' },
  luteal:     { breakfast: 'r-breakfast-eggs',    lunch: 'r-roasted-squash',    dinner: 'r-dinner-cod' },
};

const recipeById = (id) => RECIPES.find((r) => r.id === id);

// Cuisine filter options for the Recipes browse page
const RECIPE_CUISINE_FILTERS = [
  { id: 'mediterranean', label: 'Mediterranean' },
  { id: 'nordic',        label: 'Nordic' },
  { id: 'middle-east',   label: 'Middle Eastern' },
  { id: 'south-asian',   label: 'South Asian' },
  { id: 'east-asian',    label: 'Japanese & Asian' },
  { id: 'german',        label: 'European' },
  { id: 'french',        label: 'French' },
];

// Count total distinct plant foods across today's recipes
function countPlantsToday(plan) {
  const plants = new Set();
  Object.values(plan).forEach(rid => {
    const r = recipeById(rid);
    if (r) r.ingredients.filter(ing =>
      !/cod|salmon|egg|butter|ghee|kefir|yogurt/i.test(ing.item)
    ).forEach(ing => plants.add(ing.item));
  });
  return plants.size;
}

const DIETS = [
  { id: 'omnivore',      name: 'Flexible Omnivore',       desc: 'No animal protein restrictions.' },
  { id: 'flexitarian',   name: 'Flexitarian',             desc: 'Mostly plants. Occasional high-quality meat or fish.' },
  { id: 'pescatarian',   name: 'Pescatarian',             desc: 'Vegetarian foundation plus fish and seafood.' },
  { id: 'vegetarian',    name: 'Vegetarian',              desc: 'No meat, poultry, or fish. Dairy and eggs allowed.' },
  { id: 'vegan',         name: 'Vegan',                   desc: 'Strictly plant-based. No dairy, eggs, or honey.' },
  { id: 'keto',          name: 'Keto / Strict Low-Carb',  desc: 'Lower carbohydrate threshold across all meals.' },
  { id: 'mediterranean', name: 'Mediterranean',           desc: 'Olive oil, lean protein, colorful whole foods.' },
];

const ETHNICITIES = [
  { id: 'european',    label: 'European',                   note: 'Standard IR thresholds.' },
  { id: 'south-asian', label: 'South Asian',               note: 'Higher PCOS + IR prevalence — stricter carb tail at dinner.' },
  { id: 'east-asian',  label: 'East Asian',                note: 'Lower BMI threshold for IR; emphasize fermented + warming foods.' },
  { id: 'middle-east', label: 'Middle Eastern / N. African', note: 'Strong response to Mediterranean fats; watch refined carbs.' },
  { id: 'african',     label: 'African / Afro-Caribbean',  note: 'Higher gestational IR; emphasize magnesium + fiber.' },
  { id: 'latina',      label: 'Latina / Hispanic',         note: 'Genetic IR predisposition — front-load protein early.' },
  { id: 'mixed',       label: 'Mixed / Other',             note: 'Tailored to your inputs, not heritage averages.' },
  { id: 'prefer-not',  label: 'Prefer not to say',         note: 'We use the standard IR plan.' },
];

function lifeStageFor(age) {
  if (age < 20) return { id: 'teen',         label: 'Adolescent',         note: 'Hormones still establishing.' };
  if (age < 35) return { id: 'reproductive', label: 'Reproductive',       note: 'Standard 4-phase cycle syncing.' };
  if (age < 45) return { id: 'peri-early',   label: 'Early perimenopause', note: 'Cycles may shorten; insulin sensitivity drops gradually.' };
  if (age < 55) return { id: 'peri-late',    label: 'Perimenopause',      note: 'Variable cycles; magnesium + protein become critical.' };
  return              { id: 'post',           label: 'Postmenopause',      note: 'Moon-phase framework. Higher protein floor.' };
}

const CUISINES = [
  { id: 'mediterranean', name: 'Mediterranean',          hint: 'Olive oil, fish, tomatoes, herbs' },
  { id: 'middle-east',   name: 'Middle Eastern',         hint: 'Tahini, sumac, lamb, lemon' },
  { id: 'south-asian',   name: 'Indian / Ayurvedic',     hint: 'Dal, ghee, warming spices' },
  { id: 'east-asian',    name: 'East Asian',             hint: 'Miso, ginger, sesame, tofu' },
  { id: 'sea',           name: 'Southeast Asian',        hint: 'Lemongrass, fish sauce, herbs' },
  { id: 'levantine',     name: 'Levantine / Persian',    hint: 'Pomegranate, dill, yogurt' },
  { id: 'n-african',     name: 'North African',          hint: 'Harissa, preserved lemon, ras el hanout' },
  { id: 'german',        name: 'German / Central European', hint: 'Sauerkraut, rye, root vegetables' },
  { id: 'french',        name: 'French',                 hint: 'Butter, herbs de Provence, fish' },
  { id: 'mexican',       name: 'Mexican / Latin',        hint: 'Beans, lime, cilantro, mole' },
  { id: 'nordic',        name: 'Nordic',                 hint: 'Dill, salmon, rye, fermented' },
  { id: 'ethiopian',     name: 'Ethiopian',              hint: 'Berbere, teff, lentils, greens' },
];

const ALLERGENS = [
  { id: 'gluten',     name: 'Gluten / Celiac',              group: 'major' },
  { id: 'dairy',      name: 'Dairy / Milk',                 group: 'major' },
  { id: 'egg',        name: 'Egg',                          group: 'major' },
  { id: 'peanut',     name: 'Peanut',                       group: 'major' },
  { id: 'treenut',    name: 'Tree Nut',                     group: 'major' },
  { id: 'soy',        name: 'Soy',                          group: 'major' },
  { id: 'fish',       name: 'Fish & Shellfish',             group: 'major' },
  { id: 'sesame',     name: 'Sesame',                       group: 'major' },
  { id: 'lactose',    name: 'Lactose (lactose-free dairy OK)', group: 'digestive' },
  { id: 'fodmap',     name: 'Low-FODMAP',                   group: 'digestive' },
  { id: 'histamine',  name: 'Histamine',                    group: 'digestive' },
  { id: 'nightshade', name: 'Nightshade',                   group: 'digestive' },
];

const SUPERMARKETS = [
  { id: 'REWE',     name: 'REWE',           tag: 'Full-range · Bio line',       category: 'supermarket', distance: '0.4 km · Torstraße',          color: 'oklch(0.55 0.13 25)' },
  { id: 'Edeka',    name: 'Edeka',          tag: 'Full-range · regional',       category: 'supermarket', distance: '0.7 km · Linienstraße',        color: 'oklch(0.55 0.12 250)' },
  { id: 'Kaufland', name: 'Kaufland',       tag: 'Hypermarket · K-Bio',         category: 'supermarket', distance: '1.2 km · Alexanderplatz',       color: 'oklch(0.55 0.13 22)' },
  { id: 'AldiNord', name: 'ALDI Nord',      tag: 'Discount · ALDI Bio',         category: 'discount',    distance: '0.5 km · Brunnenstraße',        color: 'oklch(0.55 0.13 248)' },
  { id: 'AldiSued', name: 'ALDI Süd',       tag: 'Discount · ALDI Bio',         category: 'discount',    distance: '0.9 km · Friedrichstraße',      color: 'oklch(0.55 0.13 248)' },
  { id: 'Lidl',     name: 'Lidl',           tag: 'Discount · Bio Organic',      category: 'discount',    distance: '0.6 km · Rosenthaler Pl.',      color: 'oklch(0.58 0.13 50)' },
  { id: 'Penny',    name: 'Penny',          tag: 'Discount · Naturgut Bio',     category: 'discount',    distance: '0.8 km · Auguststraße',         color: 'oklch(0.58 0.12 30)' },
  { id: 'Netto',    name: 'Netto',          tag: 'Discount · BioBio',           category: 'discount',    distance: '1.4 km · Schönhauser',          color: 'oklch(0.55 0.13 35)' },
  { id: 'Alnatura', name: 'Alnatura',       tag: 'Bio supermarket',             category: 'organic',     distance: '1.1 km · Rosa-Luxemburg',       color: 'oklch(0.55 0.10 145)' },
  { id: 'Denns',    name: "Denn's BioMarkt", tag: 'Bio supermarket',            category: 'organic',     distance: '1.6 km · Kastanienallee',       color: 'oklch(0.50 0.10 145)' },
  { id: 'Bioco',    name: 'BIO COMPANY',    tag: 'Berlin bio chain',            category: 'organic',     distance: '0.5 km · Brunnenstraße',        color: 'oklch(0.52 0.11 140)' },
  { id: 'dm',       name: 'dm-drogerie',    tag: 'Drogerie · dmBio',            category: 'drugstore',   distance: '0.3 km · Torstraße',            color: 'oklch(0.55 0.13 75)' },
  { id: 'Rossmann', name: 'Rossmann',       tag: 'Drogerie · enerBiO',          category: 'drugstore',   distance: '0.6 km · Friedrichstraße',      color: 'oklch(0.50 0.14 22)' },
  { id: 'Mueller',  name: 'Müller',         tag: 'Drogerie · health & beauty',  category: 'drugstore',   distance: '1.5 km · Hackescher Markt',     color: 'oklch(0.55 0.13 18)' },
];

const STORE_CATEGORIES = [
  { id: 'supermarket', label: 'Supermarkets',       sub: 'Full-range, weekly shop' },
  { id: 'discount',    label: 'Discounters',        sub: 'Lower-priced staples + house-brand Bio' },
  { id: 'organic',     label: 'Organic specialists', sub: 'Whole foods, bulk bins, fresh produce' },
  { id: 'drugstore',   label: 'Drogerie',            sub: 'Seeds, oils, supplements, dry pantry' },
];

const STORE_BRAND = {
  REWE: 'REWE Bio', Edeka: 'EDEKA Bio', Kaufland: 'K-Bio',
  AldiNord: 'GUT BIO', AldiSued: 'GUT BIO', Lidl: 'Bio Organic',
  Penny: 'Naturgut Bio', Netto: 'BioBio',
  Alnatura: 'Alnatura', Denns: "Denn's", Bioco: 'BIO COMPANY',
  dm: 'dmBio', Rossmann: 'enerBiO', Mueller: 'Bio Primo',
};

const _cap = (s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : s);

function brandFor(ing, market) {
  if (ing.brand && ing.brand[market]) return ing.brand[market];
  const prefix = STORE_BRAND[market];
  if (!prefix) return ing.item;
  return `${prefix} ${_cap(ing.item)}`;
}

function bestStoreFor(item, profileMarkets) {
  const isSeedOrSupp = /seeds|sesame|sunflower|flax|pumpkin|tahini|sumac|cumin|turmeric|chili/i.test(item);
  const isFresh      = /spinach|kale|cucumber|fennel|asparagus|cilantro|dill|mint|beet|squash|avocado|lemon|cabbage|ginger|onion|sprout/i.test(item);
  const isProtein    = /cod|salmon|egg|lentil|chickpea|mung/i.test(item);
  const cats = isSeedOrSupp ? ['drugstore', 'organic', 'supermarket']
             : isFresh      ? ['organic', 'supermarket', 'discount']
             : isProtein    ? ['supermarket', 'organic', 'discount']
                            : ['supermarket', 'organic', 'discount', 'drugstore'];
  for (const cat of cats) {
    const hit = profileMarkets.find(m => SUPERMARKETS.find(s => s.id === m)?.category === cat);
    if (hit) return hit;
  }
  return profileMarkets[0];
}

// Tag display config — color per tag family
const TAG_STYLES = {
  'Gut-healing':       { bg: 'oklch(0.91 0.05 145)', fg: 'oklch(0.32 0.08 145)', bd: 'oklch(0.78 0.07 145)' },
  'Ayurvedic-spiced':  { bg: 'oklch(0.93 0.04 55)',  fg: 'oklch(0.38 0.08 50)',  bd: 'oklch(0.78 0.08 50)' },
  'Seasonal':          { bg: 'oklch(0.93 0.04 88)',  fg: 'oklch(0.38 0.08 80)',  bd: 'oklch(0.78 0.08 88)' },
  'Probiotic':         { bg: 'oklch(0.91 0.05 145)', fg: 'oklch(0.32 0.08 145)', bd: 'oklch(0.78 0.07 145)' },
  'Estrobolome':       { bg: 'oklch(0.91 0.05 145)', fg: 'oklch(0.32 0.08 145)', bd: 'oklch(0.78 0.07 145)' },
  'Fermented':         { bg: 'oklch(0.91 0.05 145)', fg: 'oklch(0.32 0.08 145)', bd: 'oklch(0.78 0.07 145)' },
  'Zero starch':       { bg: 'oklch(0.92 0.03 230)', fg: 'oklch(0.36 0.07 230)', bd: 'oklch(0.76 0.06 230)' },
  'Dinner-safe':       { bg: 'oklch(0.92 0.03 230)', fg: 'oklch(0.36 0.07 230)', bd: 'oklch(0.76 0.06 230)' },
  'Magnesium-rich':    { bg: 'oklch(0.93 0.04 88)',  fg: 'oklch(0.38 0.08 80)',  bd: 'oklch(0.78 0.08 88)' },
  'Antioxidant':       { bg: 'oklch(0.93 0.04 88)',  fg: 'oklch(0.38 0.08 80)',  bd: 'oklch(0.78 0.08 88)' },
  'Cooling':           { bg: 'oklch(0.92 0.03 230)', fg: 'oklch(0.36 0.07 230)', bd: 'oklch(0.76 0.06 230)' },
  'Protein-forward':   { bg: 'oklch(0.93 0.035 40)', fg: 'oklch(0.40 0.08 35)',  bd: 'oklch(0.76 0.08 35)' },
  'Glucose-blunted':   { bg: 'oklch(0.93 0.035 40)', fg: 'oklch(0.40 0.08 35)',  bd: 'oklch(0.76 0.08 35)' },
  'Gluten-free':       { bg: 'oklch(0.93 0.022 90)', fg: 'oklch(0.34 0.035 140)', bd: 'oklch(0.84 0.025 95)' },
  'Vegan':             { bg: 'oklch(0.91 0.05 145)', fg: 'oklch(0.32 0.08 145)', bd: 'oklch(0.78 0.07 145)' },
  'Vegetarian':        { bg: 'oklch(0.91 0.05 145)', fg: 'oklch(0.32 0.08 145)', bd: 'oklch(0.78 0.07 145)' },
  'Low-FODMAP':        { bg: 'oklch(0.93 0.022 90)', fg: 'oklch(0.34 0.035 140)', bd: 'oklch(0.84 0.025 95)' },
  'Warming':           { bg: 'oklch(0.93 0.04 55)',  fg: 'oklch(0.38 0.08 50)',  bd: 'oklch(0.78 0.08 50)' },
  'Quick':             { bg: 'oklch(0.93 0.022 90)', fg: 'oklch(0.34 0.035 140)', bd: 'oklch(0.84 0.025 95)' },
};

const tagStyle = (tag) => TAG_STYLES[tag] || { bg: 'oklch(0.93 0.022 90)', fg: 'oklch(0.34 0.035 140)', bd: 'oklch(0.84 0.025 95)' };

// Primary display tags shown on cards (exclude noisy ones)
const CARD_TAGS = ['Gut-healing', 'Ayurvedic-spiced', 'Seasonal', 'Probiotic', 'Fermented', 'Zero starch', 'Gluten-free', 'Low-FODMAP', 'Vegan', 'Vegetarian', 'Magnesium-rich', 'Antioxidant', 'Cooling', 'Warming'];

Object.assign(window, {
  PHASES, phaseForDay,
  RECIPES, recipeById, PLAN_BY_PHASE, countPlantsToday,
  DIETS, ALLERGENS, ETHNICITIES, CUISINES, lifeStageFor,
  SUPERMARKETS, STORE_CATEGORIES, STORE_BRAND,
  brandFor, bestStoreFor,
  TAG_STYLES, tagStyle, CARD_TAGS,
  RECIPE_CUISINE_FILTERS,
});
